単純な動画再生のみ対応
8k-eagle-eye/eagle-eye pull request #11
Opened 2019-07-12 13:30 UTC by m-mitsuhide

= Hooksの使い方が適切か見て欲しい
= Viewerコンポーネントにはいずれsetting.jsonのパスを渡すだけであらゆるサイトで使えるように分離したい
= 動画リストの仕様が決まってないのでパスは一旦ハードコーディング

![無題](https://user-images.githubusercontent.com/9402912/61131581-9036d980-a4f4-11e9-937d-1587820d84d3.jpg)

2019-07-13 05:16 UTC, Rokt33r requested changes

2019-07-13 05:16 UTC, Rokt33r commented on frontend/components/viewer/index.tsx
> +const Viewer: FC<ViewerProps> = props => {
FCは必ず使う必要はないです。`const Viewer = (props: ViewerProps) => {...}` で十分

2019-07-13 05:16 UTC, Rokt33r commented on frontend/components/viewer/index.tsx
> +const ViewerRoot = styled.div`
こう書くと下の関数ごとにTypeを決める必要がないはずです。

```ts
styled.div<{aspect: number}>`...`
```

2019-07-13 05:16 UTC, Rokt33r commented on frontend/components/viewer/index.tsx
> +  padding-top: ${({ aspect }: Pick<ViewerProps, 'aspect'>) => 100 / aspect}%;
なので、ここはType宣言が省略できる
```ts
({ aspect }) => ...
```

2019-07-13 05:16 UTC, Rokt33r commented on frontend/components/viewer/index.tsx
> +    const video = videoRef.current
`videoRef.current`が確実にNullではないのがわかるのであれば、（RenderingにIf文などのブランチわけは無いのが明らかなので）

`const video = videoRef.current!`でType assertionを使い、下のNull checkをしないこともできます。

2019-07-13 05:16 UTC, Rokt33r commented on frontend/components/viewer/index.tsx
> +  }, [videoRef])
`videoRef`が変わらないので、ここに入れる意味がないんです。また、このComponentは大したことをしていないので、`useCallback`を使ったらむしろ性能が悪いです。

2019-07-13 05:16 UTC, Rokt33r commented on frontend/components/viewer/index.tsx
> +  }, [videoRef])
https://kentcdodds.com/blog/usememo-and-usecallback

2019-07-15 03:52 UTC, m-mitsuhide commented on frontend/components/viewer/index.tsx
> +const Viewer: FC<ViewerProps> = props => {
修正しました

2019-07-15 03:53 UTC, m-mitsuhide commented
上記の指摘事項全て修正しました

2019-07-15 04:00 UTC, merged